name: Test Action2

runs:
  using: 'composite'
  steps:
    - name: AWS Command Test
      shell: bash
      working-directory: ./
      run: >
        aws ec2 describe-images
        --owners 099720109477 
        --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" 
        --query 'Images | sort_by(@, &CreationDate) | [-1].[Name]' 
        --output text