name: Test Action2

runs:
  using: 'composite'
  steps:
    - name: Latest AMI Image Name For ubuntu-jammy-22.04-amd64-server
      shell: bash
      working-directory: ./
      run: |
        latest_ami=$(aws ec2 describe-images \
        --owners 099720109477 \
        --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" \
        --query 'Images | sort_by(@, &CreationDate) | [-1].[Name]' \
        --output text)
        echo "LATEST_UBUNTU_AMI --> ${latest_ami}"
        echo "LATEST_UBUNTU_AMI=${latest_ami}" >> $GITHUB_ENV
        
    - name: Current Base AMI Image Name
      shell: bash
      working-directory: ./work
      run: |
        ami=$(cat ./variables.json | jq -r .ubuntu_ami_version)
        echo "BASE_UBUNTU_AMI --> ${ami}"
        echo "BASE_UBUNTU_AMI=${ami}" >> $GITHUB_ENV