name: Create PR

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Git
      shell: bash
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Set Branch Name
      shell: bash
      run: |
        git checkout -b ami-checker

    - name: Make Changes
      shell: bash
      working-directory: ./work
      run: |
        jq '.ubuntu_ami_version="${{ env.LATEST_UBUNTU_AMI }}"' ./variables.json > tmp.json && mv tmp.json ./variables.json 
  
    - name: Commit Changes
      shell: bash
      working-directory: ./
      run: |
        git add .
        git commit -m "Automated update $(date +%Y-%m-%d)"
        git push --set-upstream origin ami-checker

    # PRが既に存在するかどうかをチェック
    - name: Check If PR Already Exists
      id: check_pr_exists
      shell: bash
      run: |
        pr_title="[Ami Checker]Difference in AMI name from latest"
        base_branch=develop
        echo "pr_count=0" >> $GITHUB_OUTPUT
        echo "pr_title=abc" >> $GITHUB_OUTPUT
        echo "pr_base_branch=abc" >> $GITHUB_OUTPUT

    # PRを作成
    - name: Create PR
      if: ${{ steps.check_pr_exists.outputs.pr_count == 0 }}
      shell: bash
      run: >
        gh pr create
        -B ${{ steps.check_pr_exists.outputs.pr_base_branch }}
        -t '${{ steps.check_pr_exists.outputs.pr_title }}'
        -b ""