name: Create PR

inputs:
  body:
    required: true
    type: string
    default: ""

runs:
  using: 'composite'
  steps:
    - name: Set up Git
      shell: bash
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    # 同じタイトルのPRが既に存在するかどうかをチェック
    - name: Check If PR Already Exists
      id: check_pr_exists
      shell: bash
      run: |
        pr_title="[AMI Checker test yamamoto]Difference in AMI name from latest. (--->${{ env.Latest_AMI_Name }})"
        pr_base_branch=${{ env.BASE_BRANCH }}
        pr_count=$(gh pr list --state open --search "${pr_title} in:title" --base $pr_base_branch | wc -l)
        if [ $pr_count -ne 0 ]; then
          echo "[AMI Checker]PR already exists."
        fi
        echo "pr_count=$pr_count" >> $GITHUB_OUTPUT
        echo "pr_title=$pr_title" >> $GITHUB_OUTPUT
        echo "pr_base_branch=$pr_base_branch" >> $GITHUB_OUTPUT

    - name: Switch Branch
      id: switch_branch
      if: ${{ steps.check_pr_exists.outputs.pr_count == 0 }}
      shell: bash
      run: |
        current_datetime=$(date +'%Y%m%d%H%M%S')
        branch_name="ami-checker-${current_datetime}"
        git checkout -b "$branch_name"
        echo "branch_name=$branch_name" >> $GITHUB_OUTPUT

    # AMIの値を変更する
    - name: Make Changes
      id: make_changes
      if: ${{ steps.check_pr_exists.outputs.pr_count == 0 }}
      shell: bash
      working-directory: ./work
      run: |
        old_ami=$(jq -r '.ubuntu_ami_version' ./variables.json)
        jq '.ubuntu_ami_version="${{ env.Latest_AMI_Name }}"' ./variables.json > tmp.json && mv tmp.json ./variables.json 
        echo "old_ami=$old_ami" >> $GITHUB_OUTPUT

    - name: Commit Changes
      if: ${{ steps.check_pr_exists.outputs.pr_count == 0 }}
      shell: bash
      working-directory: ./
      run: |
        git add .
        git commit -m "Automated update $(date +%Y-%m-%d)"
        git push --set-upstream origin ${{ steps.switch_branch.outputs.branch_name }}

    # PRを作成
    - name: Create PR
      if: ${{ steps.check_pr_exists.outputs.pr_count == 0 }}
      shell: bash
      run: >
        gh pr create
        --base ${{ steps.check_pr_exists.outputs.pr_base_branch }}
        --title '${{ steps.check_pr_exists.outputs.pr_title }}'
        --body "The ubuntu_ami_version has been updated from ${{ steps.make_changes.outputs.old_ami }} to ${{ env.Latest_AMI_Name }}."