name: Check Difference in AMI Name

runs:
  using: 'composite'
  steps:
    - name: Latest AMI Name For ubuntu-jammy-22.04-amd64-server
      shell: bash
      working-directory: ./
      run: |
        ami_name=$(aws ec2 describe-images \
        --owners 099720109477 \
        --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" \
        --query 'Images | sort_by(@, &CreationDate) | [-1].[Name]' \
        --output text \
        | grep -o 'ubuntu-jammy-22.04-amd64-server-[^/]*')
        echo "Latest AMI Name --> ${ami_name}"
        echo "Latest_AMI_Name=$ami_name" >> $GITHUB_ENV
        
    - name: Current Base AMI Name
      id: current_ami_name
      shell: bash
      working-directory: ./work
      run: |
        ami_name=$(cat ./variables.json | jq -r .ubuntu_ami_version)
        echo "Current Base AMI Name --> ${ami_name}"
        echo "ami_name=$ami_name" >> $GITHUB_OUTPUT

    - name: Check Difference in AMI Name
      id: check_difference_in_ami_name
      shell: bash
      run: |
          if [ "${{ env.Latest_AMI_Name }}" != "${{ steps.current_ami_name.outputs.ami_name }}" ]; then
            echo "IS_DIFF_IN_AMI_NAME=true" >> $GITHUB_ENV
          else
            echo "IS_DIFF_IN_AMI_NAME=false" >> $GITHUB_ENV
          fi