name: Reuse AMI Monitoring

on:
  workflow_call:

jobs:
  greeting:
    name: Greeting
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-1
      BASE_BRANCH: develop
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BASE_BRANCH }}

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Check Difference in AMI Name
        uses: ./.github/actions/check_diff_in_ami

      - name: Create PR
        if: ${{ env.IS_DIFF_IN_AMI_NAME == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./.github/actions/create_pr